# Generated by Django 4.0 on 2022-01-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(default='', max_length=50)),
                ('speciality', models.CharField(default='', max_length=50)),
                ('costWard', models.CharField(default='', max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('typeGP', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=50)),
                ('covid', models.BooleanField()),
                ('army', models.BooleanField()),
                ('availableBeds', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(default=0)),
                ('timings', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
