# Generated by Django 4.0 on 2022-01-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosp',
            name='Address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hosp',
            name='hname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosp',
            name='speciality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
