# Generated by Django 4.0 on 2022-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_hosp_address_alter_hosp_hname_alter_hosp_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosp',
            name='City',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hosp',
            name='District',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hosp',
            name='State',
            field=models.CharField(default='', max_length=50),
        ),
    ]
