# Generated by Django 4.0 on 2022-01-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_hosp1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hosp',
        ),
    ]
